# Tugas 2 Aljabar Matriks

tidak mengerjakan tidak boleh masuk

-berikan penjelasan apa itu matriks
-operasi matriks
-penjumlahan,perkalian,pengurangan, transpose matriks
-membuat program untuk mengalikan matriks a dan b tanpa @

Buat matriks A dan B dengan ordo 3x3 dan matriks C dengan ordo 2x3

## Apa itu matriks?

Matriks adalah kumpulan bilangan simbol atau ekspresi yang di sebut dengan elemen, yang membentuk persegi atau persegi panjang yang di susun menurut baris dan kolom, elemen yang sejajar horizontal di sebut dengan baris matriks, dan elemen yang sejajar vertikal di sebut dengan kolom matriks

matriks biasa di namai dengan huruf kapital misalnya (A,B,C) dan seterusnya, selain itu indeks dalam matriks di sebut atau di namai dengan huruf non kapital misalnya (a,b,c) dan seterusnya.

misalnya matriks A =
$$
[[1,2,3]\\
[4,5,6]\\
[-1,-2,-3]]
$$
misalnya:
$$
[1,2,3]\\
$$
adalah baris pada matriks
dan juga:
$$
[[1,\\
[4,\\
[-1,
$$
itu di sebut sebuah kolom pada matriks

## Operasi pada matriks



## Operasi Matriks

Ada beberapa operasi yang dapat di lakukan pada matriks:
-Penjumlahan
-Perkalian
-Pengurangan
-Transpose Matriks

1. Penjumlaham Matriks
Penjumlahan pada matriks dapat di lakukan jika baris dan kolomnya sama, atau kedua matriks berordo sama
matriks satu dan yang lainnya di jumlahkan sesuai komponen komponen yang seletak
hasil matriks yang di jumlahkan akan memiliki ordo yang sama dengan 2 matriks yang di jumlahkan

2. perkalian matriks
perkalian matriks dapat di lakukan jika jumlah kolom matriks pertama sama dengan jumlah baris matriks ke dua
misalkan:\
A=
$$
\begin{bmatrix}
5 & 2\\
2 & 3
\end{bmatrix}
$$
B =
$$
\begin{bmatrix}
2 & 4 & 2\\
3 & 1 & 1
\end{bmatrix}
$$
misalkan kita mengalikan matriks A dan B dan hasilnya kita beri dengan nama matriks C\
maka C:
$$
\begin{bmatrix}
5*2+3*3 & 5*4+2*1 & 5*2+2*1\\
2*2+3*3 & 2*4+3*1 & 2*2+3*1
\end{bmatrix}
$$
jadi C:\
$$
\begin{bmatrix}
10+9 & 20+2 & 10+2\\
4+9 & 8+3 & 4+3
\end{bmatrix}
$$
C:\
$$
\begin{bmatrix}
19 & 22 & 12\\
13 & 11 & 7
\end{bmatrix}
$$

3. Pengurangan matrix
Pengurangan pada matriks dapat di lakukan jika baris dan kolomnya sama, atau kedua matriks berordo sama
matriks satu dan yang lainnya di kurangkan sesuai komponen komponen yang seletak
hasil matriks yang di kurangankan akan memiliki ordo yang sama dengan 2 matriks yang di kurangkan

4.Transpose Matriks
Transpose adalah pembuatan matriks baru dari matriks lama, caranya asdalah menukar posisi baris dengan kolom, simpelnya tranpose jika kamu punya matriks berordo 2x3 setelah di transpose akan jadi matriks 3x2\
contohnya Matriks A:\
\begin{bmatrix}
2 & 4 & 2\\
3 & 1 & 1\\
\end{bmatrix}
setelah di transpose akan menjadi:\
A:\
\begin{bmatrix}
2 & 3\\
4 & 1\\
2 & 1\\
\end{bmatrix}

In [1]:
#Penjumlahan pada matriks
## Matriks dapat di jumlahan apabila memiliki ordo yang sama

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,6,5],[-1,-2,-3]))


print(a+b)

[[8 8 8]
 [3 3 3]]


In [2]:
#Perkalian pada matriks
#Matriks bisa di kalikan jika kedua matriks memiliki jumlah baris dan kolom yang sama

import numpy as np

a = np.array(([4,2,3],
              [2,3,1],
              [0,1,1]))

b = np.array(([0.2,0.1,-0.7],
              [-0.2,0.4,0.2],
              [0.2,-0.4,0.8]))

print("matriks a: ")
print(a)
print("matriks b: ")
print(b)

c = np.dot(a,b)
print("matriks : c")
print(c)


matriks a: 
[[4 2 3]
 [2 3 1]
 [0 1 1]]
matriks b: 
[[ 0.2  0.1 -0.7]
 [-0.2  0.4  0.2]
 [ 0.2 -0.4  0.8]]
matriks : c
[[1.00000000e+00 1.11022302e-16 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [3]:
#Pengurangan pada Matriks
## Matriks dapat di jumlahan apabila memiliki ordo yang sama

a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,6,5],[-1,-2,-3]))

print(a-b)

[[-6 -4 -2]
 [ 5  7  9]]


In [4]:
#transpose matriks
## Transpose matriks membuat baris menjadi kolom
def trans(a):
   c = list(zip(*a))
   return c

def transs(a):
  for i in a:
   print(i)

a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
     ]

print("matriks sebelum transpose :")
transs(a)
print("\n")
print("matriks sesudah di transpose")
b = trans(a)
transs(b)



matriks sebelum transpose :
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


matriks sesudah di transpose
(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


In [5]:
#perkalian matruks tanpa import numpy

def matrix_kali(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("ordo eror")
        return None

    hasil = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                hasil[i][j] += matrix1[i][k] * matrix2[k][j]

    return hasil

matrix1 = [[1, 2, 3],
           [4, 5, 6]]

matrix2 = [[7, 6],
           [5, -1],
           [-2, -3]]

hasil_matrix = matrix_kali(matrix1, matrix2)

if hasil_matrix:
    print("hasil perkalian matriks")
    for row in hasil_matrix:
        print(row)


hasil perkalian matriks
[11, -5]
[41, 1]
