# tugas 3
Matriks invers\
sifat sifat matriks invers\
mencari invers dengan eliminasi gauss jordan\
solusi sistem persamaan linear dengan matriks invers\
-membuat soal sistem persamaan linear 6 variable\

Matriks invers adalah operasi yang dilakukan pada matriks persegi untuk mendapatkan matriks yang, jika dikalikan dengan matriks asal, akan menghasilkan matriks identitas. Matriks identitas adalah matriks persegi di mana semua elemen diagonal utamanya adalah 1, sedangkan elemen-elemen lainnya adalah 0.

Jika
A adalah sebuah matriks persegi berukuran
×
n×n, dan jika ada sebuah matriks
B berukuran yang sama sehingga
=
=
AB=BA=I, di mana
I adalah matriks identitas, maka
B disebut invers dari
A, dan ditulis sebagai
−
1
A
−1
 .

Jika
A memiliki invers, maka
A disebut nonsingular atau regular. Namun, jika invers dari
A tidak ada, maka
A disebut singular atau non-invertible.

Untuk matriks
2
×
2
2×2 dan
3
×
3
3×3, ada metode khusus untuk menghitung inversnya. Namun, untuk matriks
×
n×n dengan
>
3
n>3, metode pencarian inversnya biasanya melibatkan teknik-teknik seperti eliminasi Gauss-Jordan atau dekomposisi LU

Rumus untuk  mencari invers matrik.
$$
A=\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
$$\
$$
A^{-1} = \frac{1}{\det{\left(A\right)}} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]$$

$$
A^{-1} = \frac{1}{ad-bc} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]$$


Sifat Sifat Matriks invers
1. $(A^{-1})^{-1} = A$
2. $A^n$ invertibel dan $(A^n)^{-1} = (A^{-1})^n$
3. $kA$ adalah matriks invertibel dan $(kA)^{-1} = (\frac{1}{k})A^{-1}$
4. $A^T$ invertibel dan $(A^T)^{-1} = (A^{-1})^T$
5. $A$ dan $B$ keduanya matriks invertibel, maka $AB$ invertibel dan $(AB)^{-1} = B^{-1}A^{-1}$

## Solusi persamaan sistem linier dengan matrik invers

Sistem persamaan linier

$2x+3y=6$

$4x+5y=11$

Ubah dalam persamaan matrik

$$
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Langkah pertama

$$
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}^{-1}
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Langkah ke-dua

$$
\begin{bmatrix}
x\\
y
\end{bmatrix}
=\frac{1}{-2}\begin{bmatrix}
5 & -3\\
-4 & 2
\end{bmatrix}
\begin{bmatrix}
6\\
11
\end{bmatrix}
$$

Langkah ke-tiga

$$
\begin{bmatrix}
x\\
y
\end{bmatrix}
=\frac{1}{-2}\begin{bmatrix}
-3\\
-2
\end{bmatrix}
$$

Langkah ke-empat

$$
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
1.5\\
1
\end{bmatrix}
$$
import numpy as np
A = np.array([[2, 3], [4, 5]])
Ai = np.linalg.inv(A) # menghitung inverse A
b = np.array([[6], [11]])
q = np.dot(Ai, b)
print(q)
## Mencari matriks invers dengan eliminasi gauss jordan

Contoh mencari invers dengan eliminasi gauss jordan menggunakan matriks dengan ordo 3x3

Contoh soal $$A = \begin{bmatrix}
1 & 2 & 3\\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}$$

$$I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$$

Kemudian gunakan gauss jordan elimination
$$A = \begin{bmatrix}
1 & 2 & 3|1 & 0 & 0\\
0 & 1 & 4|0 & 1 & 0  \\
5 & 6 & 0|0 & 0 & 1
\end{bmatrix}$$

untuk mencari invers, gimana caranya matriks identitasnya bisa ada disebelah kiri, terserah baris berapa mau di tambahin/dikurangin/dikali/dibagi dengan baris manapun.

Kita kalikan baris pertama dengan 5 kemudian dikurangi baris ketiga
$$A = \begin{bmatrix}
1 & 2 & 3|1 & 0 & 0\\
0 & 1 & 4|0 & 1 & 0  \\
0 & -4 & -15|-5 & 0 & 1
\end{bmatrix}$$

dari matriks diatas, kita tambahkan baris ke tiga dengan 4 kali baris kedua
$$A = \begin{bmatrix}
1 & 2 & 3|1 & 0 & 0\\
0 & 1 & 4|0 & 1 & 0  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

selanjutnya kita kurangkan baris kedua dengan 4 kali baris ketiga
dan kita kurangkan juga baris pertama dengan 3 kali baris ketiga
$$A = \begin{bmatrix}
1 & 2 & 0|16 & -12 & -3\\
0 & 1 & 0|20 & -15 & -4  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

langkah terakhir kita tinggal kurangkan baris pertama dengan 2x baris kedua.hasilnya :
$$A = \begin{bmatrix}
1 & 0 & 0|-24 & 18 & 5\\
0 & 1 & 0|20 & -15 & -4  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}$$

nah yang ada disebelah kanan adalah invers dari matrik A.
jadi invers matriknya

$$A^{-1} = \begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4  \\
-5 & 4 & 1
\end{bmatrix}$$
## Membuat soal sistem persamaan linier 6 variable



## Mencari invers dengan eliminasi gauss jordan

In [1]:
import numpy as np

def gauss_jordan_inverse(matrix):
    n = len(matrix)
    augmented_matrix = np.concatenate((matrix, np.identity(n)), axis=1)

    for i in range(n):
        pivot = augmented_matrix[i][i]

        augmented_matrix[i] /= pivot

        for j in range(n):
            if i != j:
                ratio = augmented_matrix[j][i]
                augmented_matrix[j] -= ratio * augmented_matrix[i]

    inverse = augmented_matrix[:, n:]
    return inverse

matrix = np.array([[4, 7, 2],
                   [0, 3, 1],
                   [0, 5, 3]])

inverse_matrix = gauss_jordan_inverse(matrix)
print("Inverse Matrix:")
print(inverse_matrix)


Inverse Matrix:
[[ 0.25   -0.6875  0.0625]
 [ 0.      0.75   -0.25  ]
 [ 0.     -1.25    0.75  ]]


#tugas membuat soal persamaan 6 variabel


In [2]:
import numpy as np

def RowScale(A, i, scale):
    A[i] = [A[i][j]*scale for j in range(len(A[i]))]
    return A

def RowSwap(A, i, j):
    A[[i, j]] = A[[j, i]]
    return A

def RowAdd(A, i, j, scale):
    A[i] = [A[i][k] + scale*A[j][k] for k in range(len(A[i]))]
    return A

def PrintMatrix(A):
    for row in A:
        print(row)

def ReduceToIdentity(A):
    n = len(A)
    for i in range(n):
        for j in range(n):
            if i != j:
                scale = -A[j][i] / A[i][i]
                A = RowAdd(A, j, i, scale)
    for i in range(n):
        scale = 1 / A[i][i]
        A = RowScale(A, i, scale)
    return A

A = np.array([
    [2, 3, -4, 5, 3, 2, 10],
    [4, 1, 3, 5, -2, 3, 20],
    [2, 5, 4, -3, 2, -1, 30],
    [1, 3, 0, 5, -4, 3, 40],
    [1, 2, 4, 2, 6, -5, 50],
    [4, -3, 1, -1, 3, 5, 60]
])

print("Matriks Awal:")
PrintMatrix(A)
print()

A = ReduceToIdentity(A)

print("Matriks Identitas:")
PrintMatrix(A)
print()

for i, row in enumerate(A):
    print(f"x_{i+1} = {row[-1]}")


Matriks Awal:
[ 2  3 -4  5  3  2 10]
[ 4  1  3  5 -2  3 20]
[ 2  5  4 -3  2 -1 30]
[ 1  3  0  5 -4  3 40]
[ 1  2  4  2  6 -5 50]
[ 4 -3  1 -1  3  5 60]

Matriks Identitas:
[  1   0   0   0   0   0 -28]
[0 1 0 0 0 0 0]
[ 0  0  1  0  0  0 25]
[0 0 0 1 0 0 7]
[ 0  0  0  0  1  0 22]
[ 0  0  0  0  0  1 42]

x_1 = -28
x_2 = 0
x_3 = 25
x_4 = 7
x_5 = 22
x_6 = 42


In [3]:
import numpy as np

def RowSwap(A,k,l):

    m = A.shape[0]
    n = A.shape[1]

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):

    m = A.shape[0]
    n = A.shape[1]

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):

    m = A.shape[0]
    n = A.shape[1]

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

$$
x1 = 1\\
x2 = 2\\
x3 = 1\\
x4 = 3\\
x5 = 1\\
x6 = 2\\
$$
\begin{bmatrix}
x1,2x2,x3,x4,2x5,x6 = 13\\
2x1,4x2,x3,3x4,x5,x6 = 15\\
x1,x2,2x3,3x4,x5,x6 = 18\\
x1,x2,2x3,2x4,x5,x6 = 13\\
x1,2x2,x3,2x4,3x5,x6 = 13\\
x1,x2,x3,2x4,3x5,3x6 = 15\\
\end{bmatrix}

In [4]:
import numpy as np
a = np.array([[1,2,1,1,2,1,1,0,0,0,0,0],
              [2,4,1,3,1,1,0,1,0,0,0,0],
              [1,1,2,3,1,1,0,0,1,0,0,0],
              [1,1,2,2,1,1,0,0,0,1,0,0],
              [1,2,1,2,3,1,0,0,0,0,1,0],
              [1,1,1,2,3,3,0,0,0,0,0,1]])
print(a)

[[1 2 1 1 2 1 1 0 0 0 0 0]
 [2 4 1 3 1 1 0 1 0 0 0 0]
 [1 1 2 3 1 1 0 0 1 0 0 0]
 [1 1 2 2 1 1 0 0 0 1 0 0]
 [1 2 1 2 3 1 0 0 0 0 1 0]
 [1 1 1 2 3 3 0 0 0 0 0 1]]


In [5]:
a1 = RowAdd(a,2,1,-2)
print(a1)

[[ 1.  2.  1.  1.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2. -3. -3. -1. -1.  0.  1. -2.  0.  0.  0.]
 [ 1.  1.  2.  3.  1.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  2.  2.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 1.  2.  1.  2.  3.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  2.  3.  3.  0.  0.  0.  0.  0.  1.]]


In [6]:
a2 = RowAdd(a1,0,2,-1)
print(a2)

[[ 1.  2.  1.  1.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2. -3. -3. -1. -1.  0.  1. -2.  0.  0.  0.]
 [ 0. -1.  1.  2. -1.  0. -1.  0.  1.  0.  0.  0.]
 [ 1.  1.  2.  2.  1.  1.  0.  0.  0.  1.  0.  0.]
 [ 1.  2.  1.  2.  3.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  2.  3.  3.  0.  0.  0.  0.  0.  1.]]


In [7]:
a3 = RowAdd(a2,0,3,-1)
print(a3)

[[ 1.  2.  1.  1.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2. -3. -3. -1. -1.  0.  1. -2.  0.  0.  0.]
 [ 0. -1.  1.  2. -1.  0. -1.  0.  1.  0.  0.  0.]
 [ 0. -1.  1.  1. -1.  0. -1.  0.  0.  1.  0.  0.]
 [ 1.  2.  1.  2.  3.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  2.  3.  3.  0.  0.  0.  0.  0.  1.]]


In [8]:
a4 = RowAdd(a3,0,4,-1)
print(a4)

[[ 1.  2.  1.  1.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2. -3. -3. -1. -1.  0.  1. -2.  0.  0.  0.]
 [ 0. -1.  1.  2. -1.  0. -1.  0.  1.  0.  0.  0.]
 [ 0. -1.  1.  1. -1.  0. -1.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0. -1.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  2.  3.  3.  0.  0.  0.  0.  0.  1.]]


In [9]:
a5 = RowAdd(a4,0,5,-1)
print(a5)

[[ 1.  2.  1.  1.  2.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  2. -3. -3. -1. -1.  0.  1. -2.  0.  0.  0.]
 [ 0. -1.  1.  2. -1.  0. -1.  0.  1.  0.  0.  0.]
 [ 0. -1.  1.  1. -1.  0. -1.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0. -1.  0.  0.  0.  1.  0.]
 [ 0. -1.  0.  1.  1.  2. -1.  0.  0.  0.  0.  1.]]


In [10]:
a6 = RowScale(a5,1,1/2)
print(a6)

[[ 1.   2.   1.   1.   2.   1.   1.   0.   0.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [ 0.  -1.   1.   2.  -1.   0.  -1.   0.   1.   0.   0.   0. ]
 [ 0.  -1.   1.   1.  -1.   0.  -1.   0.   0.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.  -1.   0.   1.   1.   2.  -1.   0.   0.   0.   0.   1. ]]


In [11]:
a7 = RowAdd(a6,1,0,-2)
print(a7)

[[ 1.   0.   4.   4.   3.   2.   1.  -1.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [ 0.  -1.   1.   2.  -1.   0.  -1.   0.   1.   0.   0.   0. ]
 [ 0.  -1.   1.   1.  -1.   0.  -1.   0.   0.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.  -1.   0.   1.   1.   2.  -1.   0.   0.   0.   0.   1. ]]


In [12]:
a8 = RowAdd(a7,1,2,1)
print(a8)

[[ 1.   0.   4.   4.   3.   2.   1.  -1.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [ 0.   0.  -0.5  0.5 -1.5 -0.5 -1.   0.5  0.   0.   0.   0. ]
 [ 0.  -1.   1.   1.  -1.   0.  -1.   0.   0.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.  -1.   0.   1.   1.   2.  -1.   0.   0.   0.   0.   1. ]]


In [13]:
a9 = RowAdd(a8,1,3,1)
print(a9)

[[ 1.   0.   4.   4.   3.   2.   1.  -1.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [ 0.   0.  -0.5  0.5 -1.5 -0.5 -1.   0.5  0.   0.   0.   0. ]
 [ 0.   0.  -0.5 -0.5 -1.5 -0.5 -1.   0.5 -1.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.  -1.   0.   1.   1.   2.  -1.   0.   0.   0.   0.   1. ]]


In [14]:
a10 = RowAdd(a9,1,5,1)
print(a10)

[[ 1.   0.   4.   4.   3.   2.   1.  -1.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [ 0.   0.  -0.5  0.5 -1.5 -0.5 -1.   0.5  0.   0.   0.   0. ]
 [ 0.   0.  -0.5 -0.5 -1.5 -0.5 -1.   0.5 -1.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [15]:
a11 = RowScale(a10,2,-2/1)
print(a11)

[[ 1.   0.   4.   4.   3.   2.   1.  -1.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [-0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0. ]
 [ 0.   0.  -0.5 -0.5 -1.5 -0.5 -1.   0.5 -1.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [16]:
a12 = RowAdd(a11,2,0,-4)
print(a12)

[[ 1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0. ]
 [ 0.   1.  -1.5 -1.5 -0.5 -0.5  0.   0.5 -1.   0.   0.   0. ]
 [-0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0. ]
 [ 0.   0.  -0.5 -0.5 -1.5 -0.5 -1.   0.5 -1.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [17]:
a13= RowAdd(a12,5,1,-1)
print(a13)

[[ 1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0. ]
 [ 0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1. ]
 [-0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0. ]
 [ 0.   0.  -0.5 -0.5 -1.5 -0.5 -1.   0.5 -1.   1.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [18]:
a14= RowScale(a13,3,-2/1)
print(a14)

[[ 1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0. ]
 [ 0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1. ]
 [-0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0. ]
 [-0.  -0.   1.   1.   3.   1.   2.  -1.   2.  -2.  -0.  -0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [19]:
a15=RowAdd(a14,2,3,-1)
print(a15)

[[ 1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0. ]
 [ 0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1. ]
 [-0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0. ]
 [ 0.   0.   0.   2.   0.   0.   0.   0.   2.  -2.   0.   0. ]
 [ 0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0. ]
 [ 0.   0.  -1.5 -0.5  0.5  1.5 -1.   0.5 -1.   0.   0.   1. ]]


In [20]:
a16= RowScale(a15,5,-2/1)
print(a16)

[[ 1.  0.  0.  8. -9. -2. -7.  3.  2.  0.  0.  0.]
 [ 0.  1.  0. -1. -1. -2.  1.  0.  0.  0.  0. -1.]
 [-0. -0.  1. -1.  3.  1.  2. -1. -0. -0. -0. -0.]
 [ 0.  0.  0.  2.  0.  0.  0.  0.  2. -2.  0.  0.]
 [ 0.  0.  0.  1.  1.  0. -1.  0.  0.  0.  1.  0.]
 [-0. -0.  3.  1. -1. -3.  2. -1.  2. -0. -0. -2.]]


In [21]:
a17 = RowAdd(a16,2,5,-3)
print(a17)

[[  1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0.]
 [  0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1.]
 [ -0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0.]
 [  0.   0.   0.   2.   0.   0.   0.   0.   2.  -2.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   4. -10.  -6.  -4.   2.   2.   0.   0.  -2.]]


In [22]:
a18 = RowScale(a17,3,1/2)
print(a18)

[[  1.   0.   0.   8.  -9.  -2.  -7.   3.   2.   0.   0.   0.]
 [  0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1.]
 [ -0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   4. -10.  -6.  -4.   2.   2.   0.   0.  -2.]]


In [23]:
a19= RowAdd(a18,5,0,-2)
print(a19)

[[  1.   0.   0.   0.  11.  10.   1.  -1.  -2.   0.   0.   4.]
 [  0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1.]
 [ -0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   4. -10.  -6.  -4.   2.   2.   0.   0.  -2.]]


In [24]:
a20 = RowAdd(a19,3,5,-4)
print(a20)

[[  1.   0.   0.   0.  11.  10.   1.  -1.  -2.   0.   0.   4.]
 [  0.   1.   0.  -1.  -1.  -2.   1.   0.   0.   0.   0.  -1.]
 [ -0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [25]:
a21 = RowAdd(a20,3,1,1)
print(a21)

[[  1.   0.   0.   0.  11.  10.   1.  -1.  -2.   0.   0.   4.]
 [  0.   1.   0.   0.  -1.  -2.   1.   0.   1.  -1.   0.  -1.]
 [ -0.  -0.   1.  -1.   3.   1.   2.  -1.  -0.  -0.  -0.  -0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [26]:
a22 = RowAdd(a21,3,2,1)
print(a22)

[[  1.   0.   0.   0.  11.  10.   1.  -1.  -2.   0.   0.   4.]
 [  0.   1.   0.   0.  -1.  -2.   1.   0.   1.  -1.   0.  -1.]
 [  0.   0.   1.   0.   3.   1.   2.  -1.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   1.   0.  -1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [27]:
a23 = RowAdd(a22,3,4,-1)
print(a23)

[[  1.   0.   0.   0.  11.  10.   1.  -1.  -2.   0.   0.   4.]
 [  0.   1.   0.   0.  -1.  -2.   1.   0.   1.  -1.   0.  -1.]
 [  0.   0.   1.   0.   3.   1.   2.  -1.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.   0.  -1.   1.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [28]:
a24 = RowAdd(a23,4,0,-11)
print(a24)

[[  1.   0.   0.   0.   0.  10.  12.  -1.   9. -11. -11.   4.]
 [  0.   1.   0.   0.  -1.  -2.   1.   0.   1.  -1.   0.  -1.]
 [  0.   0.   1.   0.   3.   1.   2.  -1.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.   0.  -1.   1.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [29]:
a25 = RowAdd(a24,4,1,1)
print(a25)

[[  1.   0.   0.   0.   0.  10.  12.  -1.   9. -11. -11.   4.]
 [  0.   1.   0.   0.   0.  -2.   0.   0.   0.   0.   1.  -1.]
 [  0.   0.   1.   0.   3.   1.   2.  -1.   1.  -1.   0.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.   0.  -1.   1.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [30]:
a26= RowAdd(a25,4,2,-3)
print(a26)

[[  1.   0.   0.   0.   0.  10.  12.  -1.   9. -11. -11.   4.]
 [  0.   1.   0.   0.   0.  -2.   0.   0.   0.   0.   1.  -1.]
 [  0.   0.   1.   0.   0.   1.   5.  -1.   4.  -4.  -3.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.   0.  -1.   1.   1.   0.]
 [  0.   0.   0.   0. -10.  -6.  -4.   2.  -2.   4.   0.  -2.]]


In [31]:
a27 = RowAdd(a26,4,5,10)
print(a27)

[[  1.   0.   0.   0.   0.  10.  12.  -1.   9. -11. -11.   4.]
 [  0.   1.   0.   0.   0.  -2.   0.   0.   0.   0.   1.  -1.]
 [  0.   0.   1.   0.   0.   1.   5.  -1.   4.  -4.  -3.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   1.  -1.   0.   0.]
 [  0.   0.   0.   0.   1.   0.  -1.   0.  -1.   1.   1.   0.]
 [  0.   0.   0.   0.   0.  -6. -14.   2. -12.  14.  10.  -2.]]


In [32]:
a28 = RowAdd(a27,5,0,5/3)
# a = RowAdd(a27,5,0,5/3)
print(a28)
# print(a)

[[  1.           0.           0.           0.           0.
    0.         -11.33333333   2.33333333 -11.          12.33333333
    5.66666667   0.66666667]
 [  0.           1.           0.           0.           0.
   -2.           0.           0.           0.           0.
    1.          -1.        ]
 [  0.           0.           1.           0.           0.
    1.           5.          -1.           4.          -4.
   -3.           0.        ]
 [  0.           0.           0.           1.           0.
    0.           0.           0.           1.          -1.
    0.           0.        ]
 [  0.           0.           0.           0.           1.
    0.          -1.           0.          -1.           1.
    1.           0.        ]
 [  0.           0.           0.           0.           0.
   -6.         -14.           2.         -12.          14.
   10.          -2.        ]]


In [33]:
a29= RowAdd(a28,5,1,-1/3)
# b = RowAdd(a28,5,1,-1/3)
print(a29)
# print(b)

[[  1.           0.           0.           0.           0.
    0.         -11.33333333   2.33333333 -11.          12.33333333
    5.66666667   0.66666667]
 [  0.           1.           0.           0.           0.
    0.           4.66666667  -0.66666667   4.          -4.66666667
   -2.33333333  -0.33333333]
 [  0.           0.           1.           0.           0.
    1.           5.          -1.           4.          -4.
   -3.           0.        ]
 [  0.           0.           0.           1.           0.
    0.           0.           0.           1.          -1.
    0.           0.        ]
 [  0.           0.           0.           0.           1.
    0.          -1.           0.          -1.           1.
    1.           0.        ]
 [  0.           0.           0.           0.           0.
   -6.         -14.           2.         -12.          14.
   10.          -2.        ]]


In [34]:
a30= RowScale(a29,5,-1/6)
# c = RowScale(a29,5,-1/6)
print(a30)
# print(c)

[[  1.           0.           0.           0.           0.
    0.         -11.33333333   2.33333333 -11.          12.33333333
    5.66666667   0.66666667]
 [  0.           1.           0.           0.           0.
    0.           4.66666667  -0.66666667   4.          -4.66666667
   -2.33333333  -0.33333333]
 [  0.           0.           1.           0.           0.
    1.           5.          -1.           4.          -4.
   -3.           0.        ]
 [  0.           0.           0.           1.           0.
    0.           0.           0.           1.          -1.
    0.           0.        ]
 [  0.           0.           0.           0.           1.
    0.          -1.           0.          -1.           1.
    1.           0.        ]
 [ -0.          -0.          -0.          -0.          -0.
    1.           2.33333333  -0.33333333   2.          -2.33333333
   -1.66666667   0.33333333]]


In [35]:
a31 = RowAdd(a30,5,2,1)
print(a31)

[[  1.           0.           0.           0.           0.
    0.         -11.33333333   2.33333333 -11.          12.33333333
    5.66666667   0.66666667]
 [  0.           1.           0.           0.           0.
    0.           4.66666667  -0.66666667   4.          -4.66666667
   -2.33333333  -0.33333333]
 [  0.           0.           1.           0.           0.
    2.           7.33333333  -1.33333333   6.          -6.33333333
   -4.66666667   0.33333333]
 [  0.           0.           0.           1.           0.
    0.           0.           0.           1.          -1.
    0.           0.        ]
 [  0.           0.           0.           0.           1.
    0.          -1.           0.          -1.           1.
    1.           0.        ]
 [ -0.          -0.          -0.          -0.          -0.
    1.           2.33333333  -0.33333333   2.          -2.33333333
   -1.66666667   0.33333333]]


In [36]:
a32 = RowAdd(a31,5,2,-2)
print(a32)

[[  1.           0.           0.           0.           0.
    0.         -11.33333333   2.33333333 -11.          12.33333333
    5.66666667   0.66666667]
 [  0.           1.           0.           0.           0.
    0.           4.66666667  -0.66666667   4.          -4.66666667
   -2.33333333  -0.33333333]
 [  0.           0.           1.           0.           0.
    0.           2.66666667  -0.66666667   2.          -1.66666667
   -1.33333333  -0.33333333]
 [  0.           0.           0.           1.           0.
    0.           0.           0.           1.          -1.
    0.           0.        ]
 [  0.           0.           0.           0.           1.
    0.          -1.           0.          -1.           1.
    1.           0.        ]
 [ -0.          -0.          -0.          -0.          -0.
    1.           2.33333333  -0.33333333   2.          -2.33333333
   -1.66666667   0.33333333]]

In [37]:
hasil = np.array([
    [-11.33333333,2.33333333,-11,12.33333333,5.66666667,0.66666667],
    [4.66666667,-0.66666667,4,-4.66666667,-2.33333333,-0.33333333],
    [2.66666667,-0.66666667,2,-1.66666667,-1.33333333,-0.33333333],
    [0,0,1,-1,0,0],
    [-1,0,-1,1,1,0],
    [2.33333333,-0.33333333,2,-2.33333333,-1.66666667,0.33333333]
    ])

konstanta = np.array([
    [13],
    [23],
    [17],
    [14],
    [17],
    [19]
])
# print(hasil)
bukti = hasil@konstanta
print(bukti)

[[1.00000004]
 [2.00000004]
 [1.00000004]
 [3.        ]
 [1.        ]
 [1.99999996]]
